### ISSUE TITLE
Bot Stop working

### ISSUE THREAD

**Issue by Homeless4ever** [SpEcHiDe/IMDbOT#1]
Hi,

The Bot stops showing and giving any movie results, please check it and fix as soon as possible. 

Thank you

**Comment by SpEcHiDe** [comment]
please try now. something went wrong in the bot server. Sorry for the inconvenience caused.

**Comment by Homeless4ever** [comment]
Thank you for your help and making the bot working again however the bot still does not show the trailer link and IMDB link and shows unreadable characters but if you click on it many times it will disappear and shows you the links , please see the screenshot on the below link 

https://ibb.co/dKwqgXC

Thank you again for help

**Comment by SpEcHiDe** [comment]
The button is a hack (for now), till the web scrapper / api is rewritten to include the contents from the new layout of the IMDb.com page

**Comment by rikyuking** [comment]
bot not work again ... please check

**Comment by SpEcHiDe** [comment]
Telegram runined inline bots, with their server side changes. Please contact Telegram > Settings > Ask a Question.

There is nothing bot developers can do at this point.
