### ISSUE TITLE
The API is not working 

### ISSUE THREAD

**Issue by zelalem888** [SpEcHiDe/IMDbOT#13]
**The issue is with the**
- [ ] Telegram Bot
- [✅ ] API

**Describe the bug**
the API is not working I tried to get from the api but there is no response.

![image](https://github.com/user-attachments/assets/9cb3eeff-e116-48f4-822f-0f07fa49ccf8)

I have been using with brave browser in desktop.
please fix it.

**Comment by SpEcHiDe** [comment]
this might have been a temporary issue. Please try again now.
