### ISSUE TITLE
Spanish (Spain) titles/poster are not the same that Spanish (South America)

### ISSUE THREAD

**Issue by thafestco** [SpEcHiDe/IMDbOT#14]
I am from Spain and since yesterday the movie poster and the title appear in South American Spanish. Is there a way for the poster and title to appear in their original version?
The Spanish version has nothing to do with the "Spanish" of South America.
I would prefer the title and poster in English rather than that.

Is there any possibility to choose the language in the bot?

**Comment by SpEcHiDe** [comment]
![IMG_20241229_203703_650](https://github.com/user-attachments/assets/cf5a0429-115e-439c-a20e-6730cc7c25ff)


Can you show what is the `language_code` when you send start command to https://t.me/useTGxBot

**Comment by thafestco** [comment]
"language_code": "es"

For example_
"Underworld: Rise of the Lycans" in Spain is "Underworld: La rebelión de los licántropos", in Latin America is "Inframundo: La rebelión de los Lycans"

**Comment by SpEcHiDe** [comment]
I was experimenting with [this stuff](https://t.me/IMDbOTs/73?comment=3763) 
a workaround for now would be changing your language in `tg://settings/languages` to English

**Comment by thafestco** [comment]
I have tried it and it still appears "language_code": "es"

![log](https://github.com/user-attachments/assets/5493c72b-b2c2-4089-a07e-2e02c52ad307)
![settings](https://github.com/user-attachments/assets/9afa948d-13d7-4966-b095-fcd9113755e5)

**Comment by thafestco** [comment]
es-ES = Spanish from Spain
Searching in imdb Underworld 3 -> https://www.imdb.com/es-es/title/tt0834001/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_underworld

es-MX = Spanish from Mexico (used in other countries too)
Searching in imdb Underworld 3 -> https://www.imdb.com/es/title/tt0834001/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_underworld

As we can see in the urls imdb considers "es-es" as es-es (correct) and "es" as es-mx

**Comment by SpEcHiDe** [comment]
**Sorry, it was my mistake in trusting Telegram. I will fix this after 8 days.**

**Comment by SpEcHiDe** [comment]
![2024-12-29_21-40](https://github.com/user-attachments/assets/1f15b75a-4410-4fda-9319-31cb738f6cb3)

Please try again by sending `/settings` command to [CheckOTTBot](https://t.me/CheckOTTBot)

**Comment by thafestco** [comment]
Yeah, I tried with "[ES] Spain" and it seems to work correctly. Maybe it works a little slower than before when displaying the info (The image is displayed immediately but the rest of the information takes a few seconds longer than before to appear)
But it works fine for me

Thanks for your amazing work!
