### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Mohamed1419** [SpEcHiDe/IMDbOT#6]

**Comment by SpEcHiDe** [comment]
? 🤔🤔

**Comment by Mohamed1419** [comment]
sorry, meant to say it stopped working

**Comment by Mohamed1419** [comment]
hi, just to clarify, this is now inactive?

**Comment by SpEcHiDe** [comment]
What do you mean by "it is not working" ?

**Comment by Mohamed1419** [comment]
https://i-m-d-b.herokuapp.com/docs/ this link does not work. cannot make requests anymore.

**Comment by SpEcHiDe** [comment]
Heroku stopped their [FREE PLAN](https://t.me/SpEcHlDe/1632), so you can use the API URL hosted in [Cloudflare Workers](http://search.imdbot.workers.dev/).
