### ISSUE TITLE
API: Worker threw exception

### ISSUE THREAD

**Issue by arjunindia** [SpEcHiDe/IMDbOT#8]
**The issue is with the**
- [ ] Telegram Bot
- [x] API

**Describe the bug**
Worker Excepion on cloudflare

**To Reproduce**
https://search.imdbot.workers.dev/?q=lucifer
Some queries work, like https://search.imdbot.workers.dev/?q=d

**Screenshots**
![image](https://user-images.githubusercontent.com/37960163/236681410-05d83fee-8bad-4d73-9270-14acdb8a62d3.png)

**(please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Device: Electron 22.3.4

**Comment by SpEcHiDe** [comment]
Both URLs are working currently, Please re-open if issue persists.
