### ISSUE TITLE
Language selection for synopsis

### ISSUE THREAD

**Issue by MovieCollectionManager** [SpEcHiDe/IMDbOT#9]
I'ld like a feature to be able to select the language for the synopsis.

**Comment by SpEcHiDe** [comment]
multi-lingual plot outlines / synopsis aren't available on IMDb.com just yet - however, they're currently running a trial which makes them visible to certain users. The submission forms can sometimes be confusing, especially when adding a large number of items. 

It's not possible to add this to the bot at this moment. We evolve quickly and new features are added every day. We can't promise anything or give an exact timeframe, but suggestions are always welcome.
